name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud for Artifact Registry
        run: |
          gcloud auth configure-docker asia-south2-docker.pkg.dev
          gcloud auth configure-docker me-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t asia-south2-docker.pkg.dev/tensile-cogency-404310/gcr/facial-detection .
  
      - name: Push Docker image to Artifact Registry
        run: |
          docker push asia-south2-docker.pkg.dev/tensile-cogency-404310/gcr/facial-detection
          docker tag asia-south2-docker.pkg.dev/tensile-cogency-404310/gcr/facial-detection me-central1-docker.pkg.dev/tensile-cogency-404310/gcr/facial-detection
          docker push me-central1-docker.pkg.dev/tensile-cogency-404310/gcr/facial-detection
  
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy facial-recognition-service-asia-south2 --image asia-south2-docker.pkg.dev/tensile-cogency-404310/gcr/facial-detection --platform managed --region asia-south2 --allow-unauthenticated --set-env-vars DATABASE_URL=${{ secrets.DATABASE_URL }}
          gcloud run deploy facial-recognition-service-me-central1 --image me-central1-docker.pkg.dev/tensile-cogency-404310/gcr/facial-detection --platform managed --region me-central1 --allow-unauthenticated --set-env-vars DATABASE_URL=${{ secrets.DATABASE_URL }}